# Numpy Exercise  <img src = "numpy1.png">
###### Authored by T.K.Senthil Kumar

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [1]:
#Solution
import numpy as np
span=10/22
x=np.arange(10,22,span)
x

array([10.        , 10.45454545, 10.90909091, 11.36363636, 11.81818182,
       12.27272727, 12.72727273, 13.18181818, 13.63636364, 14.09090909,
       14.54545455, 15.        , 15.45454545, 15.90909091, 16.36363636,
       16.81818182, 17.27272727, 17.72727273, 18.18181818, 18.63636364,
       19.09090909, 19.54545455, 20.        , 20.45454545, 20.90909091,
       21.36363636, 21.81818182])

#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [2]:
# Solution
x1=np.arange(1,50,2)
print(x1)
len(x1)


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


25

#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [3]:
# Solution
x2=np.linspace(4,7,27)
x2



array([4.        , 4.11538462, 4.23076923, 4.34615385, 4.46153846,
       4.57692308, 4.69230769, 4.80769231, 4.92307692, 5.03846154,
       5.15384615, 5.26923077, 5.38461538, 5.5       , 5.61538462,
       5.73076923, 5.84615385, 5.96153846, 6.07692308, 6.19230769,
       6.30769231, 6.42307692, 6.53846154, 6.65384615, 6.76923077,
       6.88461538, 7.        ])

#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [4]:
# Solution
x3=np.round((np.random.uniform(7,11,size=(5,4))),2)
x3



array([[ 7.77, 10.97,  8.54,  8.94],
       [ 9.96, 10.51,  7.3 ,  7.71],
       [10.42,  8.72, 10.51,  7.77],
       [ 8.94,  9.8 ,  9.29,  8.17],
       [ 8.59,  8.81,  8.26,  8.62]])

#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [5]:
# Solution
x4=np.random.randint(5,15,(5,5))
x4


array([[10,  5, 11, 10, 12],
       [12,  8,  9, 11, 14],
       [ 5,  6,  9,  5, 13],
       [ 7,  5, 10,  6,  7],
       [13, 14, 12, 14,  5]])

#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [6]:
# Solution
x5=np.zeros(20,int)
print(x5.dtype)
print(x5)


int32
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [7]:
# Solution
x6=np.ones([5,6],dtype=np.float32)
print(x6.dtype)
print(x6)



float32
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [8]:
# Solution
x7=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])

print(x7.shape)
print(type(x7))
print(x7.dtype)



(5, 5)
<class 'numpy.ndarray'>
int32


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [9]:
# Solution
x7=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
L=len(x7)
print(L)
row=int(L/2)
col=row
x7[row,col]


5


3

#### 10. Print the all the elements of 3rd row of the matrix

In [10]:
# Solution
x7=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
r3=x7[2,:]
print(r3)


[ 5  7  3 76  3]


#### 11. Print the all the elements of 4th columns of the matrix

In [11]:
# Solution
x7=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
c4=x7[:,4]
c4


array([45,  2,  3,  6,  8])

#### 12. Print the 4 corner pixels of the matrix

In [12]:
# Solution
x7[[0,4],:][:,[0,4]]



array([[ 9, 45],
       [23,  8]])

#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [13]:
# Solution 
x7=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
mat1=x7[[0,1],:][:,[2,3]]
print('mat1 matrix: ',mat1)
mat2=x7[[3,4],:][:,[0,1]]
print('mat2 matrix:',mat2)
mat3=x7[[2,3,4],:][:,[2,3,4]]
print('mat3 matrix:',mat3)



mat1 matrix:  [[50 34]
 [34 65]]
mat2 matrix: [[ 7  8]
 [23 12]]
mat3 matrix: [[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [14]:
# Solution
m1=mat1.reshape(-1,1)
m2=mat2.reshape(-1,1)
m3=mat3.reshape(-1,1)
print(m1,m2,m3)



[[50]
 [34]
 [34]
 [65]] [[ 7]
 [ 8]
 [23]
 [12]] [[ 3]
 [76]
 [ 3]
 [ 6]
 [54]
 [ 6]
 [ 8]
 [ 5]
 [ 8]]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [15]:
# Solution
# Horizontal concatenation
print('Horizontal concatenation:')
new_m=np.concatenate((mat1,mat2),axis=1)
new_m




Horizontal concatenation:


array([[50, 34,  7,  8],
       [34, 65, 23, 12]])

In [16]:
print('Vertical concatenation')
new_m1=np.concatenate((mat1,mat2),axis=0)
new_m1

Vertical concatenation


array([[50, 34],
       [34, 65],
       [ 7,  8],
       [23, 12]])

#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [17]:
# Solution

print('Addition:')
print(mat1+mat2)
print('Subtraction:')
print(mat1-mat2)
print('Multiplication:')
print(mat1*mat2)
print('Division:')
print(mat1/mat2)


Addition:
[[57 42]
 [57 77]]
Subtraction:
[[43 26]
 [11 53]]
Multiplication:
[[350 272]
 [782 780]]
Division:
[[7.14285714 4.25      ]
 [1.47826087 5.41666667]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [28]:
# Solution
m3_del=np.delete(mat3,0,0)
delete=np.delete(m3_del,2,1)
#print(delete)
print(mat1+delete)

[[56 88]
 [42 70]]


#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [20]:
# Solution
me1=np.mean(mat1,axis=0)
me2=np.mean(mat1,axis=0)
m4=np.concatenate((me1,me2),axis=0)
m4



array([42. , 49.5, 42. , 49.5])

#### 19. Perform the matrix multiplication between m3 and m4

In [36]:
# Solution
m3_new=mat3.reshape([-1,1])
mat_mul=np.multiply(m3_new,m4)
print(mat_mul)



[[ 126.   148.5  126.   148.5]
 [3192.  3762.  3192.  3762. ]
 [ 126.   148.5  126.   148.5]
 [ 252.   297.   252.   297. ]
 [2268.  2673.  2268.  2673. ]
 [ 252.   297.   252.   297. ]
 [ 336.   396.   336.   396. ]
 [ 210.   247.5  210.   247.5]
 [ 336.   396.   336.   396. ]]


#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [57]:
# Solution
ar=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
ar.shape
max1=ar.max(axis=1)
min1=ar.min(axis=1)
print('maximum and minimum elements in the matrix\n Variance and standard deviation of the matrix are:')
(max1,min1)
var1=ar.var(axis=1)
std1=ar.std(axis=1)
(max1,min1,var1,std1)

maximum and minimum elements in the matrix
 Variance and standard deviation of the matrix are:


(array([50, 65, 76, 54, 23]),
 array([9, 2, 3, 6, 5]),
 array([214.64, 548.24, 820.16, 357.76,  39.76]),
 array([14.65059726, 23.41452541, 28.63843571, 18.91454467,  6.30555311]))

#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [40]:
# Solution 
run=np.array([[54,60,10,65],[102,2,78,32],[3,110,1,92],[56,6,12,42],[12,8,22,11]]).reshape([-1,1])
balls=np.array([[50,42,22,78],[95,8,65,43],[9,100,7,101],[27,3,11,31],[24,20,36,27]]).reshape([-1,1])
avg=run.mean(axis=1) #mean of each player
tot_run=run.sum(axis=1)  #total runs of each player
total_balls=balls.sum(axis=1)   #total no.of balls faced by each player 
strike_rate=tot_run/total_balls
srate=np.sort(strike_rate) [::-1]
averg=np.sort(avg) [::-1]
print('average runs,strike rate')
(averg,srate)



average runs,strike rate


(array([110., 102.,  92.,  78.,  65.,  60.,  56.,  54.,  42.,  32.,  22.,
         12.,  12.,  11.,  10.,   8.,   6.,   3.,   2.,   1.]),
 array([2.07407407, 2.        , 1.42857143, 1.35483871, 1.2       ,
        1.1       , 1.09090909, 1.08      , 1.07368421, 0.91089109,
        0.83333333, 0.74418605, 0.61111111, 0.5       , 0.45454545,
        0.40740741, 0.4       , 0.33333333, 0.25      , 0.14285714]))

#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [44]:
# Solution
marks = np.array([65,84,47,56,89,98,48,77,80,39])
Pass=(marks>50).sum()
Fail=(marks<50).sum()
print('No.of.Pass:',Pass,'No.of.Fail:',Fail)



No.of.Pass: 7 No.of.Fail: 3


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [55]:
# Solution
n1=marks[(marks>45) &(marks <49)]+10
print('mercy mark of students between 45,49')
print(n1)
marks1=marks[marks>80]+5
ind2=np.where(marks1>100)
marks1[ind2]=100
print('Bonus marks of students with >80')
marks1



mercy mark of students between 45,49
[57 58]
Bonus marks of students with >80


array([ 89,  94, 100])

#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [56]:
# Solution
import time
list3=[]
st=time.time()
l1=list(range(1,60001))
l2=list(range(1,60001))
for i,j in zip(l1,l2):
        list3.append((i**2+8)/j)
print((time.time()-st)*1000,'ms')





31.985759735107422 ms


#### 25. Create a Github account and upload your solution with the short write-up on Numpy

In [ ]:
# Solution
https://github.com/Kailash998/Numpy.git


